bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: {LS_ROOT}/spm_unigram10000.model
input_channels: 1
input_feat_per_channel: 40
sampling_alpha: 1.0
transforms:
  '*':
  - utterance_cmvn
  _train:
  - utterance_cmvn
vocab_filename: spm_unigram10000.txt

pitch: 
  use_pitch: False
  pitch_path: {LS_ROOT}/vq_features/pitch
  time_step: 0.01
  min_f0: 50
  max_f0: 400
  use_pov: False
  pov_path: {LS_ROOT}/vq_features/pov
  use_delta_pitch: False
  delta_pitch_path: {LS_ROOT}/vq_features/delta_pitch
  random_feats: 0

voice_quality:
  use_jitter_local: False
  jitter_local_path: {LS_ROOT}/vq_features/jitter_local
  use_shimmer_local: True
  shimmer_local_path: {LS_ROOT}/vq_features/shimmer_local
  win_length: 0.025
  win_hop: 0.01
  period_floor: 0.0001
  period_ceiling: 0.02
  max_period_factor: 1.3
  max_amplitude_factor: 1.6
  filter_frames: 151