pitch: 
  use_pitch: True
  pitch_path:
  time_step: 0.01
  min_f0: 50
  max_f0: 400
  use_pov: True
  pov_path:
  use_delta_pitch: True
  delta_pitch_path:
  random_feats: 0

voice_quality:
  use_jitter_local: True
  jitter_local_path:
  use_shimmer_local: True
  shimmer_local_path:
  win_length: 0.025
  win_hop: 0.01
  period_floor: 0.0001
  period_ceiling: 0.02
  max_period_factor: 1.3
  max_amplitude_factor: 1.6
  filter_frames: 151